env:
  commonjs: true
  es6: true
  node: true
extends:
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
rules: {}
