
steps:
    # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/entroprise-production/qa-api', '.']
    # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/entroprise-production/qa-api']
    # deploy container image to Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'qa-api', '--image', 'gcr.io/entroprise-production/qa-api', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
  images:
  - gcr.io/entroprise-production/qa-api